name: Feature Request
description: File a feature request
labels: "request"
body:
  - type: markdown
    attributes:
      value: Tech support does not belong here. You should only file an issue here if you are requesting a feature you believe would make a script better.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: script-name
    attributes:
      label: What script are you suggesting?
      description: Give us the name of your resource / script used.
    validations:
      required: true
  - type: textarea
    id: what-feature
    attributes:
      label: What feature are you suggesting?
      description: A brief description of the requested feature.
    validations:
      required: true
  - type: textarea
    id: long-explanation
    attributes:
      label: Explain all the steps and mechanics clearly and precisely.
      description: A long description of the requested feature.
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Why would this feature be useful?
      description: A brief description of why this feature would make that script better.
    validations:
      required: true
